services:
  - type: web
    name: ai-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn.conf.py
    envVars:
      - key: S3_BUCKET
        value: registered_images
